title:              "이게 한국이다! 이게 인도네시아다!"
tagline:            "찐한국생활 + 인니에서의 썰"
email:              "moun1004@gmail.com"
description:        "외국인에게 한국생활을 그리고 저의 인니경험들을 이야기하고 공유합니다."
author:             "Mario"
baseurl:            "/"
url:                "https://mounsou.github.io"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
